kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: +l6vLDgfNniehFN+KVP/tOuQ4LcimASQc/n04uGGMa0=
      - identity: {}
